version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Installing dependencies...
      - pip install awscli
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the website...
      # Add your website build commands here
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Uploading changed files to S3...
      - |
        for file in $(git diff --name-only HEAD^); do
          if [[ $file == website/* ]]; then
            aws s3 cp $file s3://wesbite/${file#website/} --acl public-read
          fi
        done